### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by akagomez** [donejs/bitballs#129]
`npm install` doesn't work on my machine. I get this error: 

```
totes:bitballs akagomez$ npm install

> bitballs@0.2.0 install /Users/akagomez/Sites/bitovi/bitballs
> node post_install.js && npm run db-migrate

module.js:341
    throw err;
    ^

Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/glob.js:44:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

My current workaround is to run: `cd public && npm install && cd - && npm run db-migrate`.

**Comment by justinbmeyer** [comment]
This is after a 

```
npm cache clean
rm -rf node_modules
rm -rf public/node_modules
npm install
```

I just verified it works for me on `staging` with NodeJS `5.4.1`.

**Comment by akagomez** [comment]
```
totes:bitballs akagomez$ npm -v
3.7.2
totes:bitballs akagomez$ node -v
v5.6.0
totes:bitballs akagomez$ npm cache clean
totes:bitballs akagomez$ rm -rf node_modules
totes:bitballs akagomez$ rm -rf public/node_modules
totes:bitballs akagomez$ npm install
npm WARN deprecated MD5@1.3.0: deprecated, use lowercase 'md5@2.x' from now on
npm WARN deprecated js-beautify@1.3.4: major indenting and html bug fixes in 1.4.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@2.4.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated babel-core@5.8.14: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated lodash@2.2.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated reverend@0.2.0: supplanted by path-to-regexp@v1.1.0#compile
npm WARN prefer global marked@0.3.5 should be installed with -g
npm WARN prefer global js-beautify@1.3.4 should be installed with -g
npm WARN prefer global jsonlint@1.6.2 should be installed with -g
npm WARN prefer global babel@5.8.35 should be installed with -g
npm WARN prefer global firebase-tools@2.2.1 should be installed with -g
npm WARN prefer global divshot-cli@1.11.0 should be installed with -g

> bufferutil@1.2.1 install /Users/akagomez/Sites/bitovi/bitballs/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> fsevents@1.0.8 install /Users/akagomez/Sites/bitovi/bitballs/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/akagomez/Sites/bitovi/bitballs/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" is installed via remote

> kerberos@0.0.11 install /Users/akagomez/Sites/bitovi/bitballs/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o

> bson@0.2.22 install /Users/akagomez/Sites/bitovi/bitballs/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bson/ext/bson.o

> sqlite3@3.1.1 install /Users/akagomez/Sites/bitovi/bitballs/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/Users/akagomez/Sites/bitovi/bitballs/node_modules/sqlite3/lib/binding/node-v47-darwin-x64/node_sqlite3.node" is installed via remote

> utf-8-validate@1.2.1 install /Users/akagomez/Sites/bitovi/bitballs/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> spawn-sync@1.0.15 postinstall /Users/akagomez/Sites/bitovi/bitballs/node_modules/spawn-sync
> node postinstall


> documentjs@0.3.6 postinstall /Users/akagomez/Sites/bitovi/bitballs/node_modules/documentjs
> install-engine-dependencies


> bitballs@0.2.0 install /Users/akagomez/Sites/bitovi/bitballs
> node post_install.js && npm run db-migrate

module.js:341
    throw err;
    ^

Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/glob.js:44:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
module.js:341
    throw err;
    ^

Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/glob.js:44:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/Users/akagomez/.node_modules/bin/npm" "install"
npm ERR! node v5.6.0
npm ERR! npm  v3.7.2
npm ERR! code ELIFECYCLE
npm ERR! bitballs@0.2.0 install: `node post_install.js && npm run db-migrate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitballs@0.2.0 install script 'node post_install.js && npm run db-migrate'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bitballs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node post_install.js && npm run db-migrate
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bitballs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bitballs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/akagomez/Sites/bitovi/bitballs/npm-debug.log
```

**Comment by justinbmeyer** [comment]
Trying with node `5.6.0` and npm `3.8.0` ....

**Comment by justinbmeyer** [comment]
.... worked.  cc @akagomez

**Comment by akagomez** [comment]
I removed `node` and `npm`, reinstalled with `nvm`, and the error went away. 

```
totes:~ akagomez$ nvm install v5.8.0
Downloading https://nodejs.org/dist/v5.8.0/node-v5.8.0-darwin-x64.tar.gz...
######################################################################## 100.0%
Now using node v5.8.0 (npm v3.7.3)
Creating default alias: default -> v5.8.0
totes:~ akagomez$ npm -v
3.7.3
totes:~ akagomez$ node -v
v5.8.0
```
