### ISSUE TITLE
Application won't start

### ISSUE THREAD

**Issue by marshallswain** [donejs/bitballs#193]
I get the following error upon running `donejs start`:

```
Bitovis-MacBook-Pro:bitballs Bitovi$ donejs start

> bitballs@0.3.1 start /Users/Bitovi/Sites/bitballs
> node index.js

Node app is running on port 5000
steal - error loading @config. [TypeError: Error loading "package.json!npm" at file:/Users/Bitovi/Sites/bitballs/public/package.json
Cannot read property 'version' of undefined]
Potentially unhandled rejection [29] Error: Error loading "bitballs/index.stache!done-autorender" at <unknown>
Error loading "done-autorender" at file:/Users/Bitovi/Sites/bitballs/public/done-autorender.js
ENOENT: no such file or directory, open '/Users/Bitovi/Sites/bitballs/public/done-autorender.js'
    at Error (native)
```

I'm running Node 5.8.0.

**Comment by marshallswain** [comment]
I've checked in the done-ssr-middleware and it's reading the package.json correctly, so I'm not sure what's going on.

**Comment by justinbmeyer** [comment]
Run donejs develop.

**Comment by marshallswain** [comment]
I still get the same error, and now an additional error for the live reload not working:

```
Bitovis-MacBook-Pro:bitballs Bitovi$ donejs develop

> bitballs@0.3.1 develop /Users/Bitovi/Sites/bitballs
> node index.js --develop

MailDev app running at 0.0.0.0:1080
/Users/Bitovi/Sites/bitballs/public/package.json!npm
Node app is running on port 5000
MailDev SMTP Server running at 0.0.0.0:1025
steal - error loading @config. [TypeError: Error loading "package.json!npm" at file:/Users/Bitovi/Sites/bitballs/public/package.json
Cannot read property 'version' of undefined]
Potentially unhandled rejection [29] Error: Error loading "bitballs/index.stache!done-autorender" at <unknown>
Error loading "done-autorender" at file:/Users/Bitovi/Sites/bitballs/public/done-autorender.js
ENOENT: no such file or directory, open '/Users/Bitovi/Sites/bitballs/public/done-autorender.js'
    at Error (native)
/Users/Bitovi/Sites/bitballs/public/node_modules/steal-tools/lib/stream/live.js:29
	var port = wss.options.server.address().port;
	                                       ^

TypeError: Cannot read property 'port' of null
    at module.exports (/Users/Bitovi/Sites/bitballs/public/node_modules/steal-tools/lib/stream/live.js:29:41)
    at Object.<anonymous> (/Users/Bitovi/Sites/bitballs/public/node_modules/steal-tools/bin/steal:83:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

**Comment by marshallswain** [comment]
I tried starting over from scratch, but arrived back at the same issue.

**Comment by justinbmeyer** [comment]
cc @matthewp @akagomez

**Comment by justinbmeyer** [comment]
@marshallswain what version of donejs?

**Comment by matthewp** [comment]
Is this master?

**Comment by matthewp** [comment]
Working for me on master with 5.3. I'll try with 5.8.

**Comment by marshallswain** [comment]
donejs --version = 0.7.2

I'm trying node 5.7, now.

**Comment by marshallswain** [comment]
5.7 worked for curtis

**Comment by matthewp** [comment]
All good for me with 5.8

<img width="682" alt="screen shot 2016-03-16 at 1 50 29 pm" src="https://cloud.githubusercontent.com/assets/361671/13822956/11bc9398-eb7e-11e5-8606-3587266a8109.png">

**Comment by marshallswain** [comment]
My node environment is apparently broken.  :(

**Comment by akagomez** [comment]
@marshallswain My node environment was giving me issues also, though the symptom was different: https://github.com/donejs/bitballs/issues/129

**Comment by marshallswain** [comment]
Thanks @akagomez.  I did the same and it works, now.  I was using n instead of nvm.  I'm having a much better experience with nvm.
