### ISSUE TITLE
Fix All Current Errors and warning.

### ISSUE THREAD

**Issue by frank-dspeed** [donejs/bitballs#318]
```
can-stache/expressions/lookup.js: Unable to find key "sessionPromise.isRejected".
can-stache/expressions/lookup.js: Unable to find key "env.NODE_ENV".
Received client connection
(node:31663) UnhandledPromiseRejectionWarning: #<Object>
(node:31663) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:31663) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In thefuture, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
can-define: Change the 'Value' definition for tournament to 'Default'.
can-define: Change the 'value' definition for isAdmin to 'default'.
(node:31663) UnhandledPromiseRejectionWarning: RangeError: Invalid array length
    at Object.update (file:/home/frank/workspace/bitballs/public/node_modules/can-view-nodelist/can-view-nodelist.js:142:36)
    at file:/home/frank/workspace/bitballs/public/node_modules/can-connect/can/tag/tag.js:135:13
    at file:/home/frank/workspace/bitballs/public/node_modules/can-observation-recorder/can-observation-recorder.js:72:21
    at Object.tagHandler (file:/home/frank/workspace/bitballs/public/node_modules/can-view-callbacks/can-view-callbacks.js:235:49)
    at Element.<anonymous> (file:/home/frank/workspace/bitballs/public/node_modules/can-stache/can-stache.js:280:21)
    at hydrateCallbacks (file:/home/frank/workspace/bitballs/public/node_modules/can-view-target/can-view-target.js:253:39)
    at Object.hydrate (file:/home/frank/workspace/bitballs/public/node_modules/can-view-target/can-view-target.js:275:4)
    at file:/home/frank/workspace/bitballs/public/node_modules/can-stache/src/html_section.js:129:20
    at file:/home/frank/workspace/bitballs/public/node_modules/can-observation-recorder/can-observation-recorder.js:72:21
    at file:/home/frank/workspace/bitballs/public/node_modules/can-stache/can-stache.js:443:19
    at file:/home/frank/workspace/bitballs/public/node_modules/can-stache/src/html_section.js:83:10
    at file:/home/frank/workspace/bitballs/public/node_modules/can-observation-recorder/can-observation-recorder.js:72:21
    at file:/home/frank/workspace/bitballs/public/components/tournament/list/list.stache:5:10
    at Constructor.setup (file:/home/frank/workspace/bitballs/public/node_modules/can-component/can-component.js:407:11)
    at Function.newInstance (file:/home/frank/workspace/bitballs/public/node_modules/can-construct/can-construct.js:287:22)
    at Constructor.init (file:/home/frank/workspace/bitballs/public/node_modules/can-construct/can-construct.js:635:29)
(node:31663) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
can-stache/expressions/lookup.js: Unable to find key "app.session".
can-stache/expressions/lookup.js: Unable to find key "scope.root.loginSession.user.email".
can-stache/expressions/lookup.js: Unable to find key "loginSession.user.password".
can-stache/expressions/lookup.js: Unable to find key "sessionPromise.isRejected".
can-stache/expressions/lookup.js: Unable to find key "env.NODE_ENV".
(node:31663) UnhandledPromiseRejectionWarning: #<Object>
(node:31663) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
Received client connection
POST USERS: creating a new user. Current count of users: 0
Error in Saving user: Checkit Errors - email: The email must be a valid email address
can-stache/expressions/lookup.js: Unable to find key "app.session".
can-stache/expressions/lookup.js: Unable to find key "scope.root.loginSession.user.email".
can-stache/expressions/lookup.js: Unable to find key "loginSession.user.password".
can-stache/expressions/lookup.js: Unable to find key "sessionPromise.isRejected".
can-stache/expressions/lookup.js: Unable to find key "env.NODE_ENV".
can-define: Change the 'value' definition for session to 'default'.
can-define: Change the 'Value' definition for user to 'Default'.
(node:31663) UnhandledPromiseRejectionWarning: #<Object>
(node:31663) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
Received client connection
POST USERS: creating a new user. Current count of users: 0
User Registration step 1 succesful
email captured: http://localhost:1080
can-stache/expressions/lookup.js: Unable to find key "app.session".
can-stache/expressions/lookup.js: Unable to find key "scope.root.loginSession.user.email".
can-stache/expressions/lookup.js: Unable to find key "loginSession.user.password".
can-stache/expressions/lookup.js: Unable to find key "sessionPromise.isRejected".
can-stache/expressions/lookup.js: Unable to find key "env.NODE_ENV".
Received client connection
can-stache/expressions/lookup.js: Unable to find key "app.session".
can-stache/expressions/lookup.js: Unable to find key "scope.root.loginSession.user.email".
can-stache/expressions/lookup.js: Unable to find key "loginSession.user.password".
can-stache/expressions/lookup.js: Unable to find key "sessionPromise.isRejected".
can-stache/expressions/lookup.js: Unable to find key "env.NODE_ENV".
can-define: Change the 'value' definition for isAdmin to 'default'.
can-define: Change the 'Value' definition for game to 'Default'.
can-define: Change the 'Value' definition for team to 'Default'.
can-define: Change the 'value' definition for playersPromise to 'default'.
can-define: Change the 'value' definition for userSelectedRound to 'default'.
can-define: Change the 'value' definition for userSelectedCourt to 'default'.
can-stache/expressions/lookup.js: Unable to find key "app.session".
can-stache/expressions/lookup.js: Unable to find key "scope.root.loginSession.user.email".
can-stache/expressions/lookup.js: Unable to find key "loginSession.user.password".
can-stache/expressions/lookup.js: Unable to find key "sessionPromise.isRejected".
can-stache/expressions/lookup.js: Unable to find key "env.NODE_ENV".
Received client connection
```

**Comment by m-mujica** [comment]
I noticed some parts of the app are not working correctly while getting the optimized build to work..

These seem to be all issues introduced in the CanJS 4.0 migration.
