### ISSUE TITLE
Techdebt: onboarding docs/work on new versions of node

### ISSUE THREAD

**Issue by josh-bitovi** [donejs/bitballs#340]
This _may_ just work on the latest node... if that's the case... this is a docs issue. If that's not the case... split out a new issue to ensure it works on the latest version of node, and follow this issue to update the docs.

This issue is to ensure the docs (README/CONTRIBUTING/SETUP) are up-to-date and easy to follow. We should ensure:
- A user can run this app in dev mode in under 5 mins
- Users know how to initiate deploys (even if someone else does them)
- Users can debug common problems encountered when setting up the app.

**Feel free to paste your env info (versions and such) and error messages in this thread!**

**Comment by tehfedaykin** [comment]
Running `donejs start` on version 6.11.0 of node produces the following error: 

`(node:52831) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error
can-bind: The child of the sticky two-way binding <input value:bind="loginSession.user.email"> is changing or converting its value when set. Conversions should only be done on the binding parent to preserve synchronization. See https://canjs.com/doc/can-stache-bindings.html#StickyBindings for more about sticky bindings
can-bind: The child of the sticky two-way binding <input value:bind="loginSession.user.password"> is changing or converting its value when set. Conversions should only be done on the binding parent to preserve synchronization. See https://canjs.com/doc/can-stache-bindings.html#StickyBindings for more about sticky bindings
index.stache:21: Unable to find key "env.NODE_ENV".


(node:52831) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
Error
    at Object.<anonymous> (/Users/jenniferwadella/Work/Bitovi/bitballs/public/node_modules/can-zone/lib/zones/timeout.js:34:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jenniferwadella/Work/Bitovi/bitballs/public/node_modules/can-zone/lib/zones/debug.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
(node:52831) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: stream.push() after EOF
(node:52831) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: stream.push() after EOF`

**Comment by josh-bitovi** [comment]
Note: `donejs start` typically used to run in prod... `donejs develop` typically used in develop.

- May solve `NODE_ENV` error:
```index.stache:21: Unable to find key "env.NODE_ENV".```

**Comment by josh-bitovi** [comment]
🔥 Hot Tip™ 🔥 Edit your comments to use `<details>` for
<details>
<summary>collapsable sections</summary>
with

lots
of
error
message
lines
here
</details>

**Comment by josh-bitovi** [comment]
Use `--debug` for more info (put this in the docs?)

**Comment by matthewp** [comment]
--debug is documented here: https://github.com/donejs/done-serve#--debug

**Comment by josh-bitovi** [comment]
It seems to work despite this.
<details>
<summary>sticky two-way binding error on `donejs develop`</summary>
➜  bitballs git:(master) donejs develop

> bitballs@0.4.1 develop /Users/josh/projects/bitovi/bitballs
> node index.js --develop

MailDev app running at 0.0.0.0:1080
Node app is running on port 5000
MailDev SMTP Server running at 0.0.0.0:1025
Live-reload server listening on port 8012
can-bind: The child of the sticky two-way binding <input value:bind="loginSession.user.email"> is changing or converting its value when set. Conversions should only be done on the binding parent to preserve synchronization. See https://canjs.com/doc/can-stache-bindings.html#StickyBindings for more about sticky bindings
can-bind: The child of the sticky two-way binding <input value:bind="loginSession.user.password"> is changing or converting its value when set. Conversions should only be done on the binding parent to preserve synchronization. See https://canjs.com/doc/can-stache-bindings.html#StickyBindings for more about sticky bindings
index.stache:21: Unable to find key "env.NODE_ENV".


Received client connection
</details>
